# name: QA

# on:
#   push:
#     branches: [ QA ]  # Runs only on QA branch
#   pull_request:
#     branches: [ QA ]  # Runs only on PRs to QA

# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest

#     steps:
#       # ✅ Checkout Repository
#       - uses: actions/checkout@v4

#       # ✅ Setup Node.js
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#           cache: 'yarn'  # Caches Yarn dependencies

#       # ✅ Install Dependencies
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile

#       # ✅ Install Playwright Browsers
#       - name: Install Playwright Browsers
#         run: yarn playwright install --with-deps

#       # ✅ Run Playwright Tests & Generate HTML Report
#       - name: Run Playwright Tests
#         run: yarn playwright test
#         env:
#           LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }} 
#           LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

#       # ✅ Upload Playwright HTML Report as Artifact
#       - name: Upload Playwright HTML Report
#         if: ${{ always() }}
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30

#       # ✅ Upload Screenshots & Traces (If Needed)
#       - name: Upload Test Results (Screenshots, Traces)
#         if: ${{ always() }}
#         uses: actions/upload-artifact@v4
#         with:
#           name: test-results
#           path: test-results/  
#           retention-days: 30


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: QA
on:
  push:
    branches: 
      - QA
  pull_request:
    branches:
      - QA
env:
  NODE_VERSION: 18.15.0
jobs:
  test:
    name: 🔬 Test
    runs-on: ubuntu-22.04
    steps:
      # ✅ Checkout Repository
      - uses: actions/checkout@v4
      
      # ✅ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm install -g yarn
      - run: corepack enable

      # ✅ Debug Repository Structure
      - name: Debug Root Directory
        run: ls -lah

      # ✅ Install Dependencies
      - name: Install dependencies
        run: yarn install
        working-directory: ./ScriptSense2

      # ✅ Install Playwright Browsers
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./ScriptSense2

      # ✅ Run Playwright Tests & Generate HTML Report
      - name: Run Playwright Tests
        run: yarn playwright test
        env:
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }} 
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        working-directory: ./ScriptSense2

      # ✅ Upload Playwright HTML Report as Artifact
      - name: Upload Playwright HTML Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ScriptSense2/playwright-report/
          retention-days: 30

      # ✅ Upload Screenshots & Traces (If Needed)
      - name: Upload Test Results (Screenshots, Traces)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ScriptSense2/test-results/
          retention-days: 30

